name: Publish to PyPI

# Only trigger manually using the GitHub Actions UI
on:
  workflow_dispatch:
    inputs:
      publish_to_pypi:
        description: 'Publish to PyPI?'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        pip install pdm
        
    - name: Build package
      run: |
        pdm build
        
    - name: List built packages
      run: |
        echo "The following packages were built:"
        ls -la dist/
        
    - name: Upload built packages
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        path: dist/

    - name: Publish to PyPI
      if: ${{ inputs.publish_to_pypi }}
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}